# Generated by Django 2.0 on 2017-12-27 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Электронная почта подтверждена')),
                ('_balance', models.IntegerField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4, verbose_name='Код активации')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Код активации',
                'verbose_name_plural': 'Коды активации',
            },
        ),
        migrations.CreateModel(
            name='AssociatedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ассоциированный email',
                'verbose_name_plural': 'Ассоциированные email',
            },
        ),
        migrations.AddField(
            model_name='activationcode',
            name='associated_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_code', to='users.AssociatedEmail'),
        ),
        migrations.AlterUniqueTogether(
            name='associatedemail',
            unique_together={('user', 'email')},
        ),
    ]
