# Generated by Django 2.0 on 2019-07-12 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLink',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.SlugField(max_length=32, verbose_name='Id ключа')),
                ('shop_name', models.CharField(max_length=128, verbose_name='Название магазина')),
                ('yur_name', models.CharField(max_length=128, verbose_name='Юр. Лицо')),
                ('client_fio', models.CharField(max_length=128, verbose_name='Фио продавца')),
                ('email', models.EmailField(max_length=128, verbose_name='E-mail')),
                ('status', models.PositiveSmallIntegerField(choices=[(10, 'ссылка отправлена'), (20, 'Ожидает проверки'), (30, 'Зачет (Золотой сертификат)'), (40, 'Зачет (Серебряный сертификат)'), (50, 'Пересдача')], default=0, verbose_name='Статус')),
                ('cert_template', models.PositiveSmallIntegerField(choices=[(0, 'Ceramic 3D'), (10, 'Wallpaper 3D'), (20, 'Kerama Marazzi 3D')], default=0, verbose_name='Шаблон сертификата')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиентская ссылка',
                'verbose_name_plural': 'Клиентские ссылки',
            },
        ),
    ]
