# Generated by Django 2.0 on 2019-07-22 11:46

import backend.apps.certification.models
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientlink',
            name='actived_to',
            field=models.DateTimeField(default=backend.apps.certification.models.default_actived_to, verbose_name='Дата окончания доступа к ссылкe'),
        ),
        migrations.AddField(
            model_name='clientlink',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientlink',
            name='modified_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата редактирования'),
        ),
        migrations.AlterField(
            model_name='clientlink',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Link ID'),
        ),
    ]
