export const USER_TOKEN_PROCESS = "USER_TOKEN_PROCESS";
export const USER_TOKEN_SUCCESS = "USER_TOKEN_SUCCESS";
export const USER_TOKEN_FAILURE = "USER_TOKEN_FAILURE";
export const USER_DATA_PROCESS = "USER_DATA_PROCESS";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FAILURE = "USER_DATA_FAILURE";